package bootiful.kubernetesclientexample;

import org.springframework.context.annotation.Configuration;
import org.springframework.nativex.hint.AccessBits;
import org.springframework.nativex.hint.TypeHint;

@Configuration
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapEnvSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ExecAction"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.models.V1ConfigClient"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1GitRepoVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerStateRunning"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PersistentVolumeClaimVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1DaemonEndpoint"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1HostAlias"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SecretProjection"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.models.V1ConfigClientList"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodSecurityContext"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerState"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Affinity"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodDNSConfigOption"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SecurityContext"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1HostPathVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1StatusCause"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PortworxVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeConfigStatus"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1HTTPHeader"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ServiceAccountTokenProjection"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Container"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Capabilities"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1DownwardAPIVolumeFile"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NFSVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1LabelSelectorRequirement"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1VolumeProjection"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1OwnerReference"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodCondition"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1FlexVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeConfigSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1TypedLocalObjectReference"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ListMeta"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EnvVar"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeSystemInfo"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeDaemonEndpoints"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.PropertySource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1AWSElasticBlockStoreVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodAntiAffinity"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodReadinessGate"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1DownwardAPIVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1LabelSelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SeccompProfile"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.Environment"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1LocalObjectReference"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1RBDVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1QuobyteVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1VolumeMount"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EphemeralVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ISCSIVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Lifecycle"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeList"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Node"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1FlockerVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1AzureFileVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SecretEnvSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeSpec"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ScaleIOVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapList"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1TCPSocketAction"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1DownwardAPIProjection"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PhotonPersistentDiskVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Handler"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1FCVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SecretKeySelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1StatusDetails"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ObjectFieldSelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1GlusterfsVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1HTTPGetAction"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Status"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.models.V1ConfigClientSpec"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Volume"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1AttachedVolume"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PersistentVolumeClaimSpec"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ObjectMeta"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Toleration"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ResourceRequirements"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EnvVarSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeStatus"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.util.Watch$Response"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.custom.IntOrString$IntOrStringAdapter"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1CephFSVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapKeySelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ProjectedVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Sysctl"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Probe"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerStateWaiting"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EnvFromSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.examples.models.V1ConfigClientStatus"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1CinderVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerImage"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1VsphereVirtualDiskVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EphemeralContainer"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1AzureDiskVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeSelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerStatus"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodIP"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerStateTerminated"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PersistentVolumeClaimTemplate"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.util.generic.GenericKubernetesApi$StatusPatch"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1VolumeDevice"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMap"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.custom.Quantity$QuantityAdapter"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1KeyToPath"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PreferredSchedulingTerm"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeAddress"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodSpec"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodAffinity"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SecretVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ManagedFieldsEntry"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeSelectorTerm"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeSelectorRequirement"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1WeightedPodAffinityTerm"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodDNSConfig"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodList"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ContainerPort"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1SELinuxOptions"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Pod"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1CSIVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeAffinity"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapNodeConfigSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodAffinityTerm"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1TopologySpreadConstraint"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1Taint"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ConfigMapProjection"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1EmptyDirVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1ResourceFieldSelector"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1NodeCondition"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1PodStatus"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1WindowsSecurityContextOptions"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1GCEPersistentDiskVolumeSource"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.extended.controller.Controller"}, access = AccessBits.ALL)
@TypeHint(typeNames = {"io.kubernetes.client.openapi.models.V1StorageOSVolumeSource"}, access = AccessBits.ALL)
public class KubernetesHints
/**
 * gotta write a NativeConfiguration to contribute these...
 *
 * Args = -H:+AddAllCharsets --enable-all-security-services --enable-https --enable-http
 *
 */
{
}
